"""2

Revision ID: 014c6b9237ee
Revises: 
Create Date: 2025-12-15 09:36:27.432509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014c6b9237ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agents', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('agents', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'department_id')
    # ### end Alembic commands ###
