"""agents3

Revision ID: 1d7fc3313155
Revises: fff6a9af793b
Create Date: 2026-01-03 23:55:34.636580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7fc3313155'
down_revision: Union[str, None] = 'fff6a9af793b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agents_is_active', table_name='agents')
    op.drop_column('agents', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_agents_is_active', 'agents', ['is_active'], unique=False)
    # ### end Alembic commands ###
