"""add constraints and indexes

Revision ID: 43ab05d0712f
Revises: 6263b2ce18c2
Create Date: 2026-01-02 01:36:08.788410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ab05d0712f'
down_revision: Union[str, None] = '6263b2ce18c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agents_department_id'), 'agents', ['department_id'], unique=False)
    op.create_index(op.f('ix_agents_hostname'), 'agents', ['hostname'], unique=False)
    op.create_index(op.f('ix_agents_is_active'), 'agents', ['is_active'], unique=False)
    op.create_index(op.f('ix_agents_is_online'), 'agents', ['is_online'], unique=False)
    op.create_unique_constraint('uq_agents_department_hostname', 'agents', ['department_id', 'hostname'])
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_unique_constraint('uq_departments_company_name', 'departments', ['company_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_departments_company_name', 'departments', type_='unique')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.drop_constraint('uq_agents_department_hostname', 'agents', type_='unique')
    op.drop_index(op.f('ix_agents_is_online'), table_name='agents')
    op.drop_index(op.f('ix_agents_is_active'), table_name='agents')
    op.drop_index(op.f('ix_agents_hostname'), table_name='agents')
    op.drop_index(op.f('ix_agents_department_id'), table_name='agents')
    # ### end Alembic commands ###
