"""4

Revision ID: 6e49c0e55685
Revises: 
Create Date: 2026-01-12 10:16:32.149054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e49c0e55685'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_departments_company_name')
    )
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('install_token', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('install_token')
    )
    op.create_index(op.f('ix_agents_company_id'), 'agents', ['company_id'], unique=False)
    op.create_index(op.f('ix_agents_department_id'), 'agents', ['department_id'], unique=False)
    op.create_index(op.f('ix_agents_hostname'), 'agents', ['hostname'], unique=False)
    op.create_index(op.f('ix_agents_is_online'), 'agents', ['is_online'], unique=False)
    op.create_table('install_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_install_tokens_token'), 'install_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_install_tokens_token'), table_name='install_tokens')
    op.drop_table('install_tokens')
    op.drop_index(op.f('ix_agents_is_online'), table_name='agents')
    op.drop_index(op.f('ix_agents_hostname'), table_name='agents')
    op.drop_index(op.f('ix_agents_department_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_company_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('companies')
    # ### end Alembic commands ###
