"""add company_id to Agent

Revision ID: 6e523b086974
Revises: 1e5fa98abbd5
Create Date: 2026-01-10 22:09:08.621710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e523b086974'
down_revision: Union[str, None] = '1e5fa98abbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('install_token', sa.String(length=64), nullable=False))
    op.alter_column('agents', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('agents', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_agents_department_hostname', 'agents', type_='unique')
    op.create_index(op.f('ix_agents_company_id'), 'agents', ['company_id'], unique=False)
    op.create_unique_constraint(None, 'agents', ['install_token'])
    op.drop_constraint('agents_department_id_fkey', 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agents', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key('agents_department_id_fkey', 'agents', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'agents', type_='unique')
    op.drop_index(op.f('ix_agents_company_id'), table_name='agents')
    op.create_unique_constraint('uq_agents_department_hostname', 'agents', ['department_id', 'hostname'], postgresql_nulls_not_distinct=False)
    op.alter_column('agents', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('agents', 'last_seen',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('agents', 'install_token')
    op.drop_column('agents', 'company_id')
    # ### end Alembic commands ###
